In [2]:
import pandas as pd
import os

In [3]:
df = pd.read_csv('groundtruth.csv') // Loading The CSV

In [4]:
df

            name  xmin  ymin  xmax  ymax
0     100001.jpg   270   186   303   239
1     100001.jpg    37   176   123   256
2     100002.jpg    57   203   178   310
3     100003.jpg   267   151   317   203
4     100004.jpg   271   163   327   205
...          ...   ...   ...   ...   ...
2491  101997.jpg   406   185   488   230
2492  101998.jpg   234   153   403   208
2493  101998.jpg   102   213   208   289
2494  101999.jpg   240   129   286   198
2495  102000.jpg   196   137   279   217

[2496 rows x 5 columns]

<h2>This Converts CSV xmin,ymin,xmax,ymax to YOLO normalized & Saves to txt</h2>

In [ ]:
for i in range(0, len(df)):
    label = df.iloc[i]['name']
    label = label[:6] # This drops '.jpg' from filename
    xmin = df.iloc[i]['xmin']
    ymin = df.iloc[i]['ymin']
    xmax = df.iloc[i]['xmax']
    ymax = df.iloc[i]['ymax']
   
    #print("label: " +label+ " xmin: " +xmin+ " ymin: " +ymin+ " xmax: " +xmax+ " ymax: " +ymax)
    
    # (xmin, ymin, xmax, ymax) to (class, x, y, width,height)
    xcen = float((xmin + xmax)) / 2 
    ycen = float((ymin + ymax)) / 2 

    w = float((xmax - xmin)) 
    h = float((ymax - ymin)) 

    # Here we are normalizing for yolo.
    # All images in DFU are 640x480
    xcen = xcen / 640
    ycen = ycen / 480
    w = w / 640
    h = h / 480
    
    xcen = str(xcen)
    ycen = str(ycen)
    w = str(w)
    h = str(h)
    
    #print("0 " +xcen+ " " +ycen+ " " +w+ " " +h)
    
    # If multiple annotaion exist in a single file then write annontaion in newline into the current file
    # Else create a new file and write annotation

    if os.path.isfile(label+'.txt'):
        print('multiple file: '+label)
        with open(label+'.txt', 'a') as fd:
            fd.write(f'\n{"0 " +xcen+ " " +ycen+ " " +w+ " " +h}')
    else:
        with open(label+'.txt', 'x') as f:
            f.write("0 " +xcen+ " " +ycen+ " " +w+ " " +h)

<h2>This Saves CSV xmin,ymin,xmax,ymax to txt</h2>

In [ ]:
for i in range(0, len(df)):
    label = df.iloc[i]['name']
    label = label[:6] # This drops '.jpg' from filename
    xmin = df.iloc[i]['xmin']
    ymin = df.iloc[i]['ymin']
    xmax = df.iloc[i]['xmax']
    ymax = df.iloc[i]['ymax']
   
    #print("label: " +label+ " xmin: " +xmin+ " ymin: " +ymin+ " xmax: " +xmax+ " ymax: " +ymax)
    
   
    xmin = str(xmin)
    ymin = str(ymin)
    xmax = str(xmax)
    ymax = str(ymax)
    
    #print("0 " +xcen+ " " +ycen+ " " +w+ " " +h)
    
    # If multiple annotaion exist in a single file then write annontaion in newline into the current file
    # Else create a new file and write annotation

    if os.path.isfile(label+'.txt'):
        print('multiple file: '+label)
        with open(label+'.txt', 'a') as fd:
            fd.write(f'\n{xmin+ " " +ymin+ " " +xmax+ " " +ymax}')
    else:
        with open(label+'.txt', 'x') as f:
            f.write(xmin+ " " +ymin+ " " +xmax+ " " +ymax)

<h2>This Part Renames All Files From 0 to N</h2>

In [2]:
import os
from os import path
import shutil

Source_Path = 'D:\CSE 499\DFU Dataset\Labels'
Destination = Source_Path
#dst_folder = os.mkdir(Destination)


def main():
    for count, filename in enumerate(os.listdir(Source_Path)):
        dst =  str(count) + ".txt"

        # rename all the files
        os.rename(os.path.join(Source_Path, filename),  os.path.join(Destination, dst))


# Driver Code
if __name__ == '__main__':
    main()

<h2>This Converts xmin, ymin, xmax, ymax txt files to YOLO format txt files</h5>

In [26]:
import os
textLocation = 'Labels/'
textDestination = 'Augmented Label/YOLOFormat/Original/'

from tqdm import tqdm
for i in tqdm(range(2000)):
    newTextLocation = textLocation + str(i) + '.txt'
    textLabel = textDestination + str(i) + '.txt'

    f = open(newTextLocation, "r")
    line_count = 0 
    for line in f:
        if line != "\n":
            line_count += 1

    #print("Total Line:",line_count) 
    f.close() # Annotation Count Ends

    f = open(newTextLocation, "r")
    while line_count > 0:
        values = f.readline()
        splitted = values.split()
        xmin = float(splitted[0])
        ymin = float(splitted[1])
        xmax = float(splitted[2])
        ymax = float(splitted[3])

        # (xmin, ymin, xmax, ymax) to (class, x, y, width,height)
        xcen = float((xmin + xmax)) / 2 
        ycen = float((ymin + ymax)) / 2 

        w = float((xmax - xmin)) 
        h = float((ymax - ymin)) 

        # Here we are normalizing for yolo.
        # All images in DFU are 640x480
        xcen = xcen / 640
        ycen = ycen / 480
        w = w / 640
        h = h / 480
    
        xcen = str(xcen)
        ycen = str(ycen)
        w = str(w)
        h = str(h)
    
        #print("0 " +xcen+ " " +ycen+ " " +w+ " " +h)
        line_count -= 1
    
        # If multiple annotaion exist in a single file then write annontaion in newline into the current file
        # Else create a new file and write annotation

        if os.path.isfile(textLabel):
            #print('multiple file: '+label)
            with open(textLabel, 'a') as fd:
                fd.write(f'\n{"0 " +xcen+ " " +ycen+ " " +w+ " " +h}')
        else:
            with open(textLabel, 'x') as fd1:
                fd1.write("0 " +xcen+ " " +ycen+ " " +w+ " " +h)
    f.close()

100%|â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆ| 2000/2000 [00:01<00:00, 1502.00it/s]